export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const TOPIC_UPDATE = 'TOPIC_UPDATE';
export const SAVED_TOPIC = 'SAVED_TOPIC';
export const SAVE_CATEGORIES = 'SAVE_CATEGORIES';
export const CHANGE_SAVE_TOPIC_STATUS = 'CHANGE_SAVE_TOPIC_STATUS';

